services:
  db:
    image: mariadb:lts
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - forgejo-net  

  forgejo:
    build: ./docker/forgejo
    container_name: forgejo-app
    depends_on:
      - db
    environment:
      FORGEJO_DOMAIN: localhost
      FORGEJO_PORT: 3000
      FORGEJO_SSH_PORT: 22
    ports:
      - "3000:3000"
      - "222:22"
    volumes:
      - forgejo-data:/data
    networks:
      - forgejo-net

volumes:
  db-data:
  forgejo-data:

networks:
  forgejo-net:
