receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      load:
      paging:
      processes:

  prometheus:
    config:
      scrape_configs:
        - job_name: 'forgejo'
          static_configs:
            - targets: ['forgejo.pp.ua']

  filelog:
    include: ["/data/log/gitea.log"]

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
    metadata_keys:
      - X-SF-Token
  resourcedetection:
    detectors: [ecs, ec2, system]
    override: true

exporters:
  # sapm:
  #   access_token: "${SPLUNK_ACCESS_TOKEN}"
  #   endpoint: https://ingest.us1.signalfx.com/v2/trace

  debug:
    verbosity: detailed

  signalfx:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    api_url: https://api.us1.signalfx.com
    ingest_url: https://ingest.us1.signalfx.com
    sync_host_metadata: true
    
service:
  pipelines:
    # traces:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [sapm]

    metrics:
      receivers: [hostmetrics, prometheus]
      processors: [batch]
      exporters: [signalfx]

    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [signalfx]